version: '3'
services:

  nginx:
    container_name: nginx
    build: services/nginx/
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./data/website:/var/www/html"
    depends_on:
      - wordpress
    networks:
      - frontend

  wordpress:
    container_name: wordpress
    build: services/wordpress/
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - "./data/website:/var/www/html"
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    environment:
      MYSQL_HOST:       ${MYSQL_HOST}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USR}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
      DOMAIN_NAME:      ${DOMAIN_NAME}
      WP_TITLE:         ${WP_TITLE}
      WP_ADMIN_USR:     ${WP_ADMIN_USR}
      WP_ADMIN_PWD:     ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
      WP_USR:           ${WP_USR}
      WP_PWD:           ${WP_PWD}
      WP_EMAIL:         ${WP_EMAIL}

  mariadb:
    container_name: mariadb
    build: services/mariadb/
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./data/mariadb:/var/lib/mysql"
    networks:
      - backend
    environment:
      MYSQL_ROOT_PWD:   ${MYSQL_ROOT_PWD}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USR}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}

  redis:
    container_name: redis
    build: services/bonus/redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend
    
networks:
  frontend:
  backend:
