version: "3.8"

services:

    nginx:
        container_name: nginx
        build: ./services/nginx
        restart: always
        ports:
            - "443:443"
            - "80:80"
        networks:
            - front
        depends_on:
            - wordpress
        volumes:
            - ./data/website:/var/www/html

    wordpress:
       container_name: wordpress
       build: ./services/wordpress
       restart: always
       ports:
           - "9000:9000"
       networks:
           - front
           - back
       depends_on:
           - mariadb
       volumes:
           - ./data/website:/var/www/html
       environment:
         MYSQL_HOST:        ${MYSQL_HOST}
         WP_DATABASE_NAME:  ${WP_DATABASE_NAME}
         WP_DATABASE_USER:  ${WP_DATABASE_USER}
         DOMAIN_NAME:       ${DOMAIN_NAME}
         WP_TITLE:          ${WP_TITLE}
         WP_ADMIN_USER:     ${WP_ADMIN_USER}
         WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
         WP_ADMIN_EMAIL:    ${WP_ADMIN_EMAIL}
         WP_USER:           ${WP_USER}
         WP_PASSWORD:       ${WP_PASSWORD}
         WP_EMAIL:          ${WP_EMAIL}

    mariadb:
      container_name: mariadb
      build: ./services/mariadb
      restart: always
      ports:
        - "3306:3306"
      networks:
        - back
      volumes:
        - ./data/mariadb:/var/lib/mysql
      environment:
        WP_DATABASE_PASSWORD: ${WP_DATABASE_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        WP_DATABASE_NAME: ${WP_DATABASE_NAME}
        WP_DATABASE_USER: ${WP_DATABASE_USER}

networks:
  front:
  back:
