# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: shovsepy <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/06/06 16:30:57 by shovsepy          #+#    #+#              #
#    Updated: 2022/06/06 16:31:39 by shovsepy         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: "3"
services:

  nginx:
    container_name: nginx
    build: services/nginx/
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./data/website:/var/www/html"
    depends_on:
      - wordpress
    networks:
      - frontend

  wordpress:
    container_name: wordpress
    build: services/wordpress/
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - "./data/website:/var/www/html"
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    environment:
      MYSQL_HOST:       ${MYSQL_HOST}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USR}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
      DOMAIN_NAME:      ${DOMAIN_NAME}
      WP_TITLE:         ${WP_TITLE}
      WP_ADMIN_USR:     ${WP_ADMIN_USR}
      WP_ADMIN_PWD:     ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
      WP_USR:           ${WP_USR}
      WP_PWD:           ${WP_PWD}
      WP_EMAIL:         ${WP_EMAIL}

  mariadb:
    container_name: mariadb
    build: services/mariadb/
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./data/mariadb:/var/lib/mysql"
    networks:
      - backend
    environment:
      MYSQL_ROOT_PWD:   ${MYSQL_ROOT_PWD}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USR}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}

  redis:
    container_name: redis
    build: services/bonus/redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

  ftp-server:
    container_name: ftp_server
    build: services/bonus/ftp-server
    restart: always
    ports:
      - "21:21"
    volumes:
      - "./data/website:/var/www/html/"
    networks:
      - backend
    environment:
      FTP_USR: ${FTP_USR}
      FTP_PWD: ${FTP_PWD}

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    security_opt:
      - no-new-privileges:true

networks:
  frontend:
  backend:

volumes:
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: ./data/website
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: ./data/mariadb
