version: 3

services:

    nginx:
        container_name: nginx
        build: ./services/nginx
        restart: always
        ports:
            - "443:443"
            - "80:80"
        networks:
            - front
        depends_on:
            - wordpress
        volumes:
            - ./data/website:/var/www/html

    wordpress:
       container_name: wordpress
       build: ./services/wordpress
       restart: always
       ports:
           - "9000:9000"
       networks:
           - front
           - back
       depends_on:
           - mariadb
       volumes:
           - ./data/website:/var/www/html

    mariadb:
      container_name: mariadb
      build: ./services/mariadb
      restart: always
      ports:
        - "3306:3306"
      networks:
        - backend
      volumes:
        ./data/mariadb:/var/lib/mysql

  networks:
    frontend:
    backend:
